---
title: "Stochastic Auto Reserving"
author: "Minseok Han"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(DBI)
library(RSQLite)
library(reshape2)
library(ChainLadder)
library(openxlsx)
```

```{r}
conn <- dbConnect(RSQLite::SQLite(), "CommAuto.db")

query <- "
  SELECT AccidentYear, DevelopmentLag, SUM(CumPaidLoss) as CumPaidLoss
  FROM commercial_auto
  WHERE AccidentYear + DevelopmentLag <= 2008 -- Mask the future
  GROUP BY AccidentYear, DevelopmentLag
"
industry_data <- dbGetQuery(conn, query)

dbDisconnect(conn)
```

```{r}
tri_matrix <- dcast(industry_data, AccidentYear ~ DevelopmentLag, value.var = "CumPaidLoss")
tri <- as.triangle(as.matrix(tri_matrix[, -1]))
dimnames(tri)[[1]] <- tri_matrix$AccidentYear
```

```{r}
set.seed(88125)
boot_model <- BootChainLadder(tri, R = 1000, process.distr = "gamma")
bootstrap_summary <- summary(boot_model)
print(bootstrap_summary)
plot(boot_model)
```

```{r}
# summary <- as.data.frame(bootstrap_summary$Totals)

# wb <- loadWorkbook("Commercial_Auto_Reserving_Dashboard.xlsx")
# if (!"Bootstrap Summary" %in% names(wb)) addWorksheet(wb, sheetName = "Bootstrap Summary")
# writeData(wb, sheet = "Bootstrap Summary", x = summary, rowNames = TRUE)
# saveWorkbook(wb, "Commercial_Auto_Reserving_Dashboard.xlsx", overwrite = TRUE)
```


